### ISSUE TITLE
Number of Columns

### ISSUE THREAD

**Issue by voteleobrown** [CodyHouse/schedule-template#1]
Not an issue, per se, but when adding two days, to make the total number 7 I'm getting a second row of days. In the situation the hours, rather than restarting for the second row, continue and split half on row one half one row two. I have not yet figured out what is dictating this behavior. 

EDIT: Nevermind, found it.

(starting at line 182 of css/style.css)

```css
@media only screen and (min-width: 800px) {
  .cd-schedule .events {
    float: left;
    width: 100%;
  }
  .cd-schedule .events .events-group {
    width: 20%; /* This 20% is the culprit. 100%/20% = 5. For 7 days, 14% works */
    float: left;
    border: 1px solid #EAEAEA;
    /* reset style */
    margin-bottom: 0;
}
```
